package com.novartis.ecrs.model.am.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 02 19:04:24 IST 2015
// ---------------------------------------------------------------------
public interface ECRSAppModule extends ApplicationModule {
    void copyCurrentRiskRelation(Long srcRiskId, Long destCrsId);

    void copyRoutineDefinition(Long crsId);

    void deleteCrs();

    List fetchDatabases();

    List fetchDesignees();

    void filterCRSContent(String userInRole, String userName, boolean isInboxDisable);

    void initRiskRelation(Long crsId, String status);

    boolean refreshRepository(Long crsId);

    boolean activateCrs(Long pCRSId, String pReasonForChange);

    boolean modifyCrs(Long pCRSId, String pReasonForChange);

    boolean reactivateCrs(Long pCRSId, String pReasonForChange);

    boolean retireCrs(Long pCRSId, String pReasonForChange);
}
