package com.novartis.ecrs.model.am;


import com.novartis.ecrs.model.am.common.ECRSAppModule;
import com.novartis.ecrs.model.constants.ModelConstants;
import com.novartis.ecrs.model.lov.UserRoleVORowImpl;
import com.novartis.ecrs.model.view.ECrsSearchVORowImpl;
import com.novartis.ecrs.model.view.HierarchyChildDetailVOImpl;
import com.novartis.ecrs.model.view.trans.CompoundTransientVOImpl;
import com.novartis.ecrs.model.view.trans.DomainsTransientVOImpl;
import com.novartis.ecrs.model.view.trans.RiskPurposeTransientVOImpl;
import com.novartis.ecrs.model.view.trans.RolesTransientVOImpl;
import com.novartis.ecrs.model.view.trans.StateTransientVOImpl;
import com.novartis.ecrs.model.view.trans.UserRolesTransientVOImpl;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jdbc.OracleCallableStatement;

import org.apache.log4j.Logger;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 11 22:09:07 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ECRSAppModuleImpl extends ApplicationModuleImpl implements ECRSAppModule {
    
    public static final Logger logger = Logger.getLogger(ECRSAppModuleImpl.class);
    /**
     * This is the default constructor (do not remove).
     */
    public ECRSAppModuleImpl() {
    }

    /**
     * Container's getter for CrsContentVO.
     * @return CrsContentVO
     */
    public ViewObjectImpl getCrsContentVO() {
        return (ViewObjectImpl)findViewObject("CrsContentVO");
    }


    /**
     * Container's getter for CrsUserRolesVO.
     * @return CrsUserRolesVO
     */
    public ViewObjectImpl getCrsUserRolesVO() {
        return (ViewObjectImpl)findViewObject("CrsUserRolesVO");
    }
    
    /**
     * Fetch the List of Designees (BSL's) to show as an LOV on the UI.
     *
     * @return - List of Designees
     */
    public List fetchDesignees(){
        List<UserRoleVORowImpl> designeeList = new ArrayList<UserRoleVORowImpl>();
        ViewObject userVO = this.getUserRoleVO();
        //Where clause appended to fetch only BSL's
        userVO.setNamedWhereClauseParam("roleName",ModelConstants.ROLE_BSL);
        userVO.executeQuery();
        if(userVO.getEstimatedRowCount() > 0){
            RowSetIterator rs = userVO.createRowSetIterator(null);
            while(rs.hasNext()){
                Row row = rs.next();
                //Adding all BSL usernames to the list.
                designeeList.add((UserRoleVORowImpl)row);
            }
            rs.closeRowSetIterator();
        }
        return designeeList;
    }
    
    /**
     * Fetch the list of Database available (like MEDDRA, ARGUS) to show them as an LOV on the UI.
     * 
     * @return
     */
    public List fetchDatabases(){
        List<String> databaseList = new ArrayList<String>();
        ViewObject databaseVO = this.getCrsDatabasesLOVVO();
        databaseVO.executeQuery();
        if(databaseVO.getEstimatedRowCount() > 0){
            RowSetIterator rs = databaseVO.createRowSetIterator(null);
            while(rs.hasNext()){
                Row row = rs.next();
                //Adding all database names to the List being returned
                databaseList.add((String)row.getAttribute("DatabaseName"));
            }
            rs.closeRowSetIterator();
        }
        return databaseList;
    }

    /**
     * Container's getter for CompoundTransientVO.
     * @return CompoundTransientVO
     */
    public CompoundTransientVOImpl getCompoundTransientVO() {
        return (CompoundTransientVOImpl)findViewObject("CompoundTransientVO");
    }

    /**
     * Container's getter for CrsCompoundVO.
     * @return CrsCompoundVO
     */
    public ViewObjectImpl getCrsCompoundVO() {
        return (ViewObjectImpl)findViewObject("CrsCompoundVO");
    }

    /**
     * Container's getter for RiskPurposeTransientVO.
     * @return RiskPurposeTransientVO
     */
    public RiskPurposeTransientVOImpl getRiskPurposeTransientVO() {
        return (RiskPurposeTransientVOImpl)findViewObject("RiskPurposeTransientVO");
    }

    /**
     * Container's getter for CrsRiskPurposesVO.
     * @return CrsRiskPurposesVO
     */
    public ViewObjectImpl getCrsRiskPurposesVO() {
        return (ViewObjectImpl)findViewObject("CrsRiskPurposesVO");
    }

    /**
     * Container's getter for RolesTransientVO.
     * @return RolesTransientVO
     */
    public RolesTransientVOImpl getRolesTransientVO() {
        return (RolesTransientVOImpl)findViewObject("RolesTransientVO");
    }

    /**
     * Container's getter for CrsRolesVO.
     * @return CrsRolesVO
     */
    public ViewObjectImpl getCrsRolesVO() {
        return (ViewObjectImpl)findViewObject("CrsRolesVO");
    }

    /**
     * Container's getter for ECrsSearchVO1.
     * @return ECrsSearchVO1
     */
    public ViewObjectImpl getECrsSearchVO() {
        return (ViewObjectImpl)findViewObject("ECrsSearchVO");
    }
    
    /**
     * 
     * This method fetches the CRS's the logged in user can see based on the search criteria entered in the form.
     * 
     * @param userInRole - logged in user's role
     * @param userName - logged in user's name
     * @param isInboxDisable - Inbox checkbox (enabled or disabled)
     */
    public void filterCRSContent(String userInRole,String userName,boolean isInboxDisable, String flowType){
        String whereClause = "";
        ViewObjectImpl searchVO = this.getECrsSearchVO();
        
        //IF INBOX SELECTED - PENDING ONES IN USER'S QUEUE
        ECrsSearchVORowImpl row = null;
//        if (isInboxDisable) {
//            whereClause +=
//                    "RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING +
//            "' AND ";
//            
//            //if user role is MQM - set state = 2 and 3 , TASL - SET State = 4 , ML - set state = 5
//            // set appropriate column names
//            if (ModelConstants.ROLE_MQM.equals(userInRole))
//                whereClause += "STATE_ID IN (2,3)";
//            else if (ModelConstants.ROLE_TASL.equals(userInRole))
//                whereClause += "STATE_ID = 4 AND TASL_NAME ='"+userName+"'";
//            else if (ModelConstants.ROLE_ML.equals(userInRole))
//                whereClause += "STATE_ID = 5 AND MEDICAL_LEAD_NAME ='"+userName+"'";          
//            else if (ModelConstants.ROLE_BSL.equals(userInRole))
//                whereClause += "STATE_ID NOT IN (2,4,5) AND ( BSL_NAME ='"+userName+"' OR DESIGNEE LIKE '%"+ userName+"%')";     
//
//        // INBOX NOT SELECTED
//        } else {

            row = (ECrsSearchVORowImpl)searchVO.getCurrentRow();

            //Appending Where clause based on the entered search criteria in the form.s
            if (row.getReleaseStatus() != null)
                whereClause += "RELEASE_STATUS_FLAG = '" + row.getReleaseStatus() + "' AND ";
            if (row.getCompoundType() != null)
                whereClause += "CRS_COMPOUND_TYPE ='" + row.getCompoundType() + "' AND ";
            if (row.getCompoundCodeId() != null)
                whereClause += "COMPOUND_ID =" + row.getCompoundCodeId() + " AND ";
            if (row.getState() != null)
                whereClause += "STATE_ID =" + row.getState() + " AND ";     
            if (row.getGenericName() != null)
                whereClause += "GENERIC_NAME LIKE '%" + row.getGenericName() + "%' AND ";
            if (row.getTradeName() != null)
                whereClause += "TRADE_NAME LIKE '%" + row.getTradeName() + "%' AND ";
            if (row.getIndication() != null)
                whereClause += "INDICATION LIKE '%" + row.getIndication() + "%' AND ";
            if (row.getMarketed() != null)
                whereClause += "IS_MARKETED_FLAG ='" + row.getMarketed() + "' AND ";
            if (row.getDesignee() != null)
                whereClause += "DESIGNEE LIKE '%" + row.getDesignee() + "%' AND ";
            if (row.getCrsTasl() != null)
                whereClause += "TASL_NAME ='" + row.getCrsTasl() + "' AND ";
            if (row.getCrsMedicalLead() != null)
                whereClause += "MEDICAL_LEAD_NAME ='" + row.getCrsMedicalLead() + "' AND ";            
            if (row.getCrsBsl() != null)
                whereClause += "BSL_NAME = '" + row.getCrsBsl() + "' AND ";
            if (row.getCrsName() != null)
                whereClause += "CRS_NAME LIKE '%" + row.getCrsName() + "%' AND ";
            if (row.getCrsId() != null)
                whereClause += "CRS_ID LIKE '%" + row.getCrsId() + "%' AND ";
            
            if(flowType != null && "S".equalsIgnoreCase(flowType)){
            // DATA SECUTIRY - BSL/MQM/TASL/ML can view only their corresponding records
            if (ModelConstants.ROLE_MQM.equals(userInRole))
                whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID IN (2,3)) OR RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "')";
            if (ModelConstants.ROLE_TASL.equals(userInRole))
                whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID = 4 AND TASL_NAME ='"+userName+"') OR RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "')";
            if (ModelConstants.ROLE_ML.equals(userInRole))
                whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID = 5 AND MEDICAL_LEAD_NAME ='"+userName+"') OR RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "')";        
            if (ModelConstants.ROLE_BSL.equals(userInRole))
                whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID NOT IN (2,4,5) AND ( BSL_NAME ='"+userName+"' OR DESIGNEE LIKE '%"+ userName+"%')) OR RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "')";        
            }
            else{
                if (ModelConstants.ROLE_MQM.equals(userInRole))
                    whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID IN (2,3)) OR RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "')";
                if (ModelConstants.ROLE_TASL.equals(userInRole))
                    whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID = 4 AND TASL_NAME ='"+userName+"') OR (RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "' AND TASL_NAME ='"+userName+"'))";
                if (ModelConstants.ROLE_ML.equals(userInRole))
                    whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID = 5 AND MEDICAL_LEAD_NAME ='"+userName+"') OR (RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "' AND MEDICAL_LEAD_NAME ='"+userName+"'))";        
                if (ModelConstants.ROLE_BSL.equals(userInRole))
                    whereClause += "((RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_PENDING + "' AND STATE_ID NOT IN (2,4,5) AND ( BSL_NAME ='"+userName+"' OR DESIGNEE LIKE '%"+ userName+"%')) OR (RELEASE_STATUS_FLAG = '" + ModelConstants.STATUS_CURRENT + "' AND ( BSL_NAME ='"+userName+"' OR DESIGNEE LIKE '%"+ userName+"%')))";       
            }
//        }
        
        if (whereClause.endsWith("AND "))
            whereClause =
                    whereClause.substring(0, whereClause.length() - 4) + "";
        
        ViewObjectImpl crsContentVO = null;
        //Hit Base table to fetch current records and Staging table to fetch pending records.
        if (ModelConstants.STATUS_PENDING.equals(row.getReleaseStatus())) {
            crsContentVO = this.getCrsContentVO();           
            this.getCrsContentBaseVO().executeEmptyRowSet();
        } else {
            crsContentVO = this.getCrsContentBaseVO();          
            this.getCrsContentVO().executeEmptyRowSet();
        }
        crsContentVO.setWhereClause(whereClause);
        crsContentVO.executeQuery();
        crsContentVO.setWhereClause(null);
        crsContentVO.applyViewCriteria(null);
        
    }

    /**
     * Container's getter for CrsStateVO.
     * @return CrsStateVO
     */
    public ViewObjectImpl getCrsStateVO() {
        return (ViewObjectImpl)findViewObject("CrsStateVO");
    }

    /**
     * Container's getter for StateTransientVO.
     * @return StateTransientVO
     */
    public StateTransientVOImpl getStateTransientVO() {
        return (StateTransientVOImpl)findViewObject("StateTransientVO");
    }

    /**
     * Container's getter for UserRolesTransientVO.
     * @return UserRolesTransientVO
     */
    public UserRolesTransientVOImpl getUserRolesTransientVO() {
        return (UserRolesTransientVOImpl)findViewObject("UserRolesTransientVO");
    }

    /**
     * Container's getter for CrsRiskVO.
     * @return CrsRiskVO
     */
    public ViewObjectImpl getCrsRiskVO() {
        return (ViewObjectImpl)findViewObject("CrsRiskVO");
    }


    /**
     * Container's getter for CrsRiskRelationVO.
     * @return CrsRiskRelationVO
     */
    public ViewObjectImpl getCrsRiskRelationVO() {
        return (ViewObjectImpl)findViewObject("CrsRiskRelationVO");
    }

    /**
     * Container's getter for CrsRiskDefinitionsVO.
     * @return CrsRiskDefinitionsVO
     */
    public ViewObjectImpl getCrsRiskDefinitionsVO() {
        return (ViewObjectImpl)findViewObject("CrsRiskDefinitionsVO");
    }

    /**
     * Container's getter for CrsRiskRelationToRiskDefintionLink1.
     * @return CrsRiskRelationToRiskDefintionLink1
     */
    public ViewLinkImpl getCrsRiskRelationToRiskDefintionLink1() {
        return (ViewLinkImpl)findViewLink("CrsRiskRelationToRiskDefintionLink1");
    }
    
    /**
     *
     * @param crsId -- ID of the CRS that is being created or updated
     * 
     * Info : Metdod to show the risk definitions (if any) for the selected CRS on load of risk definitions page.
     */
    public void initRiskRelation(Long crsId, String status){
        //Fetching current records from base table
        if(status != null && ModelConstants.BASE_FACET.equals(status)){
            ViewObject riskBaseVO = this.getCrsRiskBaseVO();
            //for the selected CRSID
            riskBaseVO.setWhereClause("CRS_ID = "+crsId);
            riskBaseVO.executeQuery();
            ViewObject riskVO = this.getCrsRiskVO();
            riskVO.executeEmptyRowSet();
        }
        //Fetching pending records from staging table
        else{
            ViewObject riskVO = this.getCrsRiskVO();
            //for the selected CRSID
            riskVO.setWhereClause("CRS_ID = "+crsId);
            riskVO.executeQuery();
            ViewObject riskBaseVO = this.getCrsRiskBaseVO();
            riskBaseVO.executeEmptyRowSet();
        }
    }

    /**
     * Container's getter for CRSCurrentAndPendingCRSReport1.
     * @return CRSCurrentAndPendingCRSReport1
     */
    public ViewObjectImpl getCRSCurrentPendingCRSReport() {
        return (ViewObjectImpl)findViewObject("CRSCurrentPendingCRSReport");
    }

    /**
     * Container's getter for MedDRAComponentsReport1.
     * @return MedDRAComponentsReport1
     */
    public ViewObjectImpl getMedDRAComponentsReport() {
        return (ViewObjectImpl)findViewObject("MedDRAComponentsReport");
    }

    /**
     * Container's getter for MedDRAStandardReport1.
     * @return MedDRAStandardReport1
     */
    public ViewObjectImpl getMedDRAStandardReport() {
        return (ViewObjectImpl)findViewObject("MedDRAStandardReport");
    }

    /**
     * Container's getter for NumberOfCompoundCrsReport1.
     * @return NumberOfCompoundCrsReport1
     */
    public ViewObjectImpl getNumberOfCompoundCrsReport() {
        return (ViewObjectImpl)findViewObject("NumberOfCompoundCrsReport");
    }

    /**
     * Container's getter for RiskDefinitionsSafetyTopicReport1.
     * @return RiskDefinitionsSafetyTopicReport1
     */
    public ViewObjectImpl getRiskDefSafetyTopicReport() {
        return (ViewObjectImpl)findViewObject("RiskDefSafetyTopicReport");
    }

    /**
     * Container's getter for TotalNumOfADRsReport1.
     * @return TotalNumOfADRsReport1
     */
    public ViewObjectImpl getTotalNumOfADRsReport() {
        return (ViewObjectImpl)findViewObject("TotalNumOfADRsReport");
    }

    /**
     * Container's getter for TotalNumOfSafetyTopicsReport1.
     * @return TotalNumOfSafetyTopicsReport1
     */
    public ViewObjectImpl getTotalNumOfSafetyTopicsReport() {
        return (ViewObjectImpl)findViewObject("TotalNumOfSafetyTopicsReport");
    }
    
    /**
     *
     * @param crsId -- ID of the CRS to which the routine crs needs to be copied
     * 
     * Info : Method to copy the ROUTINE CRS risk definitons to the newly created CRS.
     */
    public void copyRoutineDefinition(Long crsId){
        logger.info("--In copyRoutineDefinition--crsId==" + crsId);
        ViewObject relationVO = this.getCrsRiskRelationVO();
        ViewObject definitionVO = this.getCrsRiskDefinitionsVO();
        ViewObjectImpl crsContentVO = this.getFetchCrsContentBaseVO();
        //Fetch the crs details for CRS with name as ROUTINE
        //crsContentVO.setWhereClause("CRS_NAME = 'ROUTINE'");
        crsContentVO.setWhereClause("CRS_COMPOUND_CODE = 'ROUTINE'");
        crsContentVO.executeQuery();
        logger.info("-- Crs Routine query ==" + crsContentVO.getQuery());
        crsContentVO.setWhereClause(null);
        crsContentVO.applyViewCriteria(null);
        if(crsContentVO.getEstimatedRowCount() > 0){
            Row crsRow = crsContentVO.first();
            Long srcCrsId = (Long)crsRow.getAttribute("CrsId");
            logger.info("--Routine CrsId ==" + srcCrsId);
            ViewObject crsRiskVO = this.getCrsRiskBaseVO();
            //Fetch risk relations for ROUTINE CRS in sorted order.
            crsRiskVO.setWhereClause("CRS_ID = "+srcCrsId);
            crsRiskVO.setSortBy("CrsRiskId asc");
            crsRiskVO.executeQuery();
            logger.info("-- Crs Routine Risk query ==" + crsRiskVO.getQuery());
            Long crsRiskId = null;
            Long newCrsRiskId = null;
            if(crsRiskVO.getEstimatedRowCount() > 0){
                RowSetIterator rs = crsRiskVO.createRowSetIterator(null);
                //Iterating through each row in the FLAT VIEW
                while(rs.hasNext()){
                    Row row = rs.next();
                    //If it is a risk relation row, set all attributes required.
                    if(crsRiskId == null || !crsRiskId.equals((Long)row.getAttribute("CrsRiskId"))){
                        crsRiskId = (Long)row.getAttribute("CrsRiskId");
                        Row relationRow = relationVO.createRow();
                        relationRow.setAttribute("CrsId", crsId);
//                        relationRow.setAttribute("DataDomain", row.getAttribute("DataDomain"));
//                        relationRow.setAttribute("DatabaseList", row.getAttribute("DatabaseList"));
                        relationRow.setAttribute("DomainId", fetchDomainIdFromName((String)row.getAttribute("DataDomain")));
                        String riskPurposeList = (String)row.getAttribute("RiskPurposeList");
                        //Storing risk purposes as comma separated.
                        if(riskPurposeList != null && riskPurposeList.endsWith(",")){
                            riskPurposeList = riskPurposeList.substring(0,riskPurposeList.length()-1);
                        }
                        relationRow.setAttribute("RiskPurposeList", riskPurposeList);
                        relationRow.setAttribute("SafetyTopicOfInterest", row.getAttribute("SafetyTopicOfInterest"));
                        relationRow.setAttribute("SocDictContentEntryTs", row.getAttribute("SocDictContentEntryTs"));
                        relationRow.setAttribute("SocDictContentId", row.getAttribute("SocDictContentId"));
                        relationRow.setAttribute("SocTerm", row.getAttribute("SocTerm"));
                        relationRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                        relationVO.insertRow(relationRow);
                        if (null != row.getAttribute("CrsRiskDefnId")){
                            Row definitionRow = definitionVO.createRow();
                            newCrsRiskId = (Long)relationRow.getAttribute("CrsRiskId");
                            definitionRow.setAttribute("CrsRiskId", newCrsRiskId);
                            definitionRow.setAttribute("MeddraQualifier", row.getAttribute("MeddraQualifier"));
                            definitionRow.setAttribute("CrsQualifier", row.getAttribute("MeddraQualifier"));
                            definitionRow.setAttribute("MeddraCode", row.getAttribute("MeddraCode"));
                            definitionRow.setAttribute("MeddraLevel", row.getAttribute("MeddraLevel"));
                            definitionRow.setAttribute("MeddraTerm", row.getAttribute("MeddraTerm"));
                            definitionRow.setAttribute("MeddraVersion", row.getAttribute("MeddraVersion"));
                            definitionRow.setAttribute("MeddraVersionDate", row.getAttribute("MeddraVersionDate"));
                            // definitionRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                            definitionRow.setAttribute("MeddraDict", row.getAttribute("MeddraDict"));
                            definitionRow.setAttribute("MeddraExtension", row.getAttribute("MeddraExtension"));
                            definitionRow.setAttribute("TmsDictContentEntryTs", row.getAttribute("TmsDictContentEntryTs"));
                            definitionRow.setAttribute("TmsDictContentId", row.getAttribute("TmsDictContentId"));
                            definitionRow.setAttribute("TmsEndTs", row.getAttribute("TmsEndTs"));
                            definitionRow.setAttribute("MeddraQualifierUpdFlag", row.getAttribute("MeddraQualifierUpdFlag"));
                            //                        definitionRow.setAttribute("TmsUpdateFlag", row.getAttribute("TmsUpdateFlag"));
                            //                        definitionRow.setAttribute("TmsUpdateFlagDt", row.getAttribute("TmsUpdateFlagDt"));
                            definitionVO.insertRow(definitionRow);
                        }
                        
                    } else { //If it is a risk defintion row, set all attributes required.
                        Row definitionRow = definitionVO.createRow();
                        definitionRow.setAttribute("CrsRiskId", newCrsRiskId);
                        definitionRow.setAttribute("MeddraQualifier", row.getAttribute("MeddraQualifier"));
                        definitionRow.setAttribute("MeddraCode", row.getAttribute("MeddraCode"));
                        definitionRow.setAttribute("MeddraLevel", row.getAttribute("MeddraLevel"));
                        definitionRow.setAttribute("MeddraTerm", row.getAttribute("MeddraTerm"));
                        definitionRow.setAttribute("MeddraVersion", row.getAttribute("MeddraVersion"));
                        definitionRow.setAttribute("MeddraVersionDate", row.getAttribute("MeddraVersionDate"));
                        //definitionRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                        definitionRow.setAttribute("MeddraDict", row.getAttribute("MeddraDict"));
                        definitionRow.setAttribute("MeddraExtension", row.getAttribute("MeddraExtension"));
                        definitionRow.setAttribute("TmsDictContentEntryTs", row.getAttribute("TmsDictContentEntryTs"));
                        definitionRow.setAttribute("TmsDictContentId", row.getAttribute("TmsDictContentId"));
                        definitionRow.setAttribute("TmsEndTs", row.getAttribute("TmsEndTs"));
                        definitionRow.setAttribute("CrsQualifier", row.getAttribute("MeddraQualifier"));
                        definitionRow.setAttribute("MeddraQualifierUpdFlag", row.getAttribute("MeddraQualifierUpdFlag"));
//                        definitionRow.setAttribute("TmsUpdateFlag", row.getAttribute("TmsUpdateFlag"));
//                        definitionRow.setAttribute("TmsUpdateFlagDt", row.getAttribute("TmsUpdateFlagDt"));
                        definitionVO.insertRow(definitionRow); 
                    }
                }
                rs.closeRowSetIterator();
            } else {
                logger.info("--In copyRoutineDefinition--No routine risk definitions found");
            }
//            this.getDBTransaction().commit();
        } else {
            logger.info("--In copyRoutineDefinition--No routine CRS found");
        }
    }

    /**
     * Container's getter for CRSCountPerMeddraReportVO.
     * @return CRSCountPerMeddraReportVO
     */
    public ViewObjectImpl getCRSCountPerMeddraReportVO() {
        return (ViewObjectImpl)findViewObject("CRSCountPerMeddraReportVO");
    }

    /**
     * Container's getter for CrsDatabasesLOVVO.
     * @return CrsDatabasesLOVVO
     */
    public ViewObjectImpl getCrsDatabasesLOVVO() {
        return (ViewObjectImpl)findViewObject("CrsDatabasesLOVVO");
    }

    /**
     * Container's getter for HierarchySearchVO.
     * @return HierarchySearchVO
     */
    public ViewObjectImpl getHierarchySearchVO() {
        return (ViewObjectImpl)findViewObject("HierarchySearchVO");
    }
    
    /**
     * 
     * Info : Method to delete the current CRS, which internally deletes risk relations and risk definitions attached to it.
     */
    public void deleteCrs(){
        ViewObject crsContentVO = this.getCrsContentVO();
        ViewObject relationVO = this.getCrsRiskRelationVO();
        ViewObject definitionVO = this.getCrsRiskDefinitionsVO();
        Row crsRow = crsContentVO.getCurrentRow();
        if(crsRow != null){
            Long crsId = (Long)crsRow.getAttribute("CrsId");
            //Fetch the required CRS details (that needs to be deleted)
            relationVO.setWhereClause("CRS_ID = "+crsId);
            relationVO.executeQuery();
            //Fetch all risk relations.
            if(relationVO.getEstimatedRowCount() > 0){
                RowSetIterator relationRs = relationVO.createRowSetIterator(null);
                while(relationRs.hasNext()){
                    Row relationRow = relationRs.next();
                    relationVO.setCurrentRow(relationRow);
//                    Long riskId = (Long)relationRow.getAttribute("CrsRiskId");
//                    definitionVO.setWhereClause("CRS_RISK_ID = "+riskId);
//                    definitionVO.executeQuery();
                    //Fetch all risk defintions
                    if(definitionVO.getEstimatedRowCount() > 0){
                        RowSetIterator definitionRs = definitionVO.createRowSetIterator(null);
                        while(definitionRs.hasNext()){
                            Row definitionRow = definitionRs.next();
                            //delete risk defintions
                            definitionRow.remove();
                        }
                    }
                    //delete risk relations
                    relationRow.remove();
                }
            }
            //delete crs
            crsRow.remove();
            //commit
            this.getDBTransaction().commit();
        }
    }

    /**
     * Container's getter for FetchCrsContentVO.
     * @return FetchCrsContentVO
     */
    public ViewObjectImpl getFetchCrsContentVO() {
        return (ViewObjectImpl)findViewObject("FetchCrsContentVO");
    }

    /**
     * Container's getter for HierarchyChildVO.
     * @return HierarchyChildVO
     */
    public ViewObjectImpl getHierarchyChildVO() {
        return (ViewObjectImpl)findViewObject("HierarchyChildVO");
    }


    /**
     * Container's getter for CopyCrsRiskVO.
     * @return CopyCrsRiskVO
     */
    public ViewObjectImpl getCopyCrsRiskVO() {
        return (ViewObjectImpl)findViewObject("CopyCrsRiskVO");
    }


    /**
     * This method copies the risk relation to the current selected CRS, this is used in the Copy Risk Definitions popup on the UI.
     *
     * @param srcRiskId - Source Risk Relation (copied from)
     * @param destCrsId - Destination Risk Relation (copied to)
     */
    public void copyCurrentRiskRelation(Long srcRiskId, Long destCrsId) {
        logger.info("--In copyCurrentRiskRelation--srcRiskId==" + srcRiskId);
        ViewObject relationVO = this.getCrsRiskRelationVO();
        ViewObject definitionVO = this.getCrsRiskDefinitionsVO();
        ViewObject crsRiskVO = this.getFetchCrsRiskVO();
        //Fetch the source risk relation details
        crsRiskVO.setWhereClause("CRS_RISK_ID = " + srcRiskId);
        crsRiskVO.executeQuery();
        Long crsRiskId = null;
        Long newCrsRiskId = null;
        if (crsRiskVO.getEstimatedRowCount() > 0) {
            RowSetIterator rs = crsRiskVO.createRowSetIterator(null);
            //Iterating over each row in the FLAT VIEW
            while (rs.hasNext()) {
                Row row = rs.next();
                //If it is a risk relation(parent) row, set all attributes from source
                if (crsRiskId == null || !crsRiskId.equals((Long)row.getAttribute("CrsRiskId"))) {
                    crsRiskId = (Long)row.getAttribute("CrsRiskId");
                    Row relationRow = relationVO.createRow();
                    relationRow.setAttribute("CrsId", destCrsId);
//                    relationRow.setAttribute("DataDomain", row.getAttribute("DataDomain"));
                    relationRow.setAttribute("DomainId", fetchDomainIdFromName((String)row.getAttribute("DataDomain")));
//                    relationRow.setAttribute("DatabaseList", row.getAttribute("DatabaseList"));
                    //Risk purpose list stored as comma separated
                    String riskPurposeList = (String)row.getAttribute("RiskPurposeList");
                    if (riskPurposeList != null && riskPurposeList.endsWith(",")) {
                        riskPurposeList = riskPurposeList.substring(0, riskPurposeList.length() - 1);
                    }
                    relationRow.setAttribute("RiskPurposeList", riskPurposeList);
                    relationRow.setAttribute("SafetyTopicOfInterest", row.getAttribute("SafetyTopicOfInterest"));
                    relationRow.setAttribute("SocDictContentEntryTs", row.getAttribute("SocDictContentEntryTs"));
                    relationRow.setAttribute("SocDictContentId", row.getAttribute("SocDictContentId"));
                    relationRow.setAttribute("SocTerm", row.getAttribute("SocTerm"));
                    relationRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                    relationVO.insertRow(relationRow);
                    if (null != row.getAttribute("CrsRiskDefnId")){
                        Row definitionRow = definitionVO.createRow();
                        
                        newCrsRiskId = (Long)relationRow.getAttribute("CrsRiskId");
                        definitionRow.setAttribute("CrsRiskId", newCrsRiskId);
                        definitionRow.setAttribute("MeddraQualifier", row.getAttribute("MeddraQualifier"));
                        definitionRow.setAttribute("CrsQualifier", row.getAttribute("MeddraQualifier"));
                        definitionRow.setAttribute("MeddraCode", row.getAttribute("MeddraCode"));
                        definitionRow.setAttribute("MeddraLevel", row.getAttribute("MeddraLevel"));
                        definitionRow.setAttribute("MeddraTerm", row.getAttribute("MeddraTerm"));
                        definitionRow.setAttribute("MeddraVersion", row.getAttribute("MeddraVersion"));
                        definitionRow.setAttribute("MeddraVersionDate", row.getAttribute("MeddraVersionDate"));
                        //definitionRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                        definitionRow.setAttribute("MeddraDict", row.getAttribute("MeddraDict"));
                        definitionRow.setAttribute("MeddraExtension", row.getAttribute("MeddraExtension"));
                        definitionRow.setAttribute("TmsDictContentEntryTs", row.getAttribute("TmsDictContentEntryTs"));
                        definitionRow.setAttribute("TmsDictContentId", row.getAttribute("TmsDictContentId"));
                        definitionRow.setAttribute("TmsEndTs", row.getAttribute("TmsEndTs"));
                        definitionRow.setAttribute("MeddraQualifierUpdFlag", row.getAttribute("MeddraQualifierUpdFlag"));
                        //                    definitionRow.setAttribute("TmsUpdateFlag", row.getAttribute("TmsUpdateFlag"));
                        //                    definitionRow.setAttribute("TmsUpdateFlagDt", row.getAttribute("TmsUpdateFlagDt"));
                        definitionVO.insertRow(definitionRow);
                    }
                } else { //If it is a risk definitons (child) row, set all attributes from source
                    Row definitionRow = definitionVO.createRow();
                    definitionRow.setAttribute("CrsRiskId", newCrsRiskId);
                    definitionRow.setAttribute("MeddraQualifier", row.getAttribute("MeddraQualifier"));
                    definitionRow.setAttribute("CrsQualifier", row.getAttribute("MeddraQualifier"));
                    definitionRow.setAttribute("MeddraCode", row.getAttribute("MeddraCode"));
                    definitionRow.setAttribute("MeddraLevel", row.getAttribute("MeddraLevel"));
                    definitionRow.setAttribute("MeddraTerm", row.getAttribute("MeddraTerm"));
                    definitionRow.setAttribute("MeddraVersion", row.getAttribute("MeddraVersion"));
                    definitionRow.setAttribute("MeddraVersionDate", row.getAttribute("MeddraVersionDate"));
                   // definitionRow.setAttribute("SearchCriteriaDetails", row.getAttribute("SearchCriteriaDetails"));
                    definitionRow.setAttribute("MeddraDict", row.getAttribute("MeddraDict"));
                    definitionRow.setAttribute("MeddraExtension", row.getAttribute("MeddraExtension"));
                    definitionRow.setAttribute("TmsDictContentEntryTs", row.getAttribute("TmsDictContentEntryTs"));
                    definitionRow.setAttribute("TmsDictContentId", row.getAttribute("TmsDictContentId"));
                    definitionRow.setAttribute("TmsEndTs", row.getAttribute("TmsEndTs"));
                    definitionRow.setAttribute("MeddraQualifierUpdFlag", row.getAttribute("MeddraQualifierUpdFlag"));
//                    definitionRow.setAttribute("TmsUpdateFlag", row.getAttribute("TmsUpdateFlag"));
//                    definitionRow.setAttribute("TmsUpdateFlagDt", row.getAttribute("TmsUpdateFlagDt"));
                    definitionVO.insertRow(definitionRow);
                }
            }
            rs.closeRowSetIterator();
        }
    }

    /**
     * Container's getter for FetchCrsRiskVO.
     * @return FetchCrsRiskVO
     */
    public ViewObjectImpl getFetchCrsRiskVO() {
        return (ViewObjectImpl)findViewObject("FetchCrsRiskVO");
    }

    /**
     * Container's getter for HierarchyChildDetailVO1.
     * @return HierarchyChildDetailVO1
     */
    public ViewObjectImpl getHierarchyChildDetailVO1() {
        return (ViewObjectImpl)findViewObject("HierarchyChildDetailVO1");
    }

    /**
     * Container's getter for HierarchyChildSelfLink1.
     * @return HierarchyChildSelfLink1
     */
    public ViewLinkImpl getHierarchyChildSelfLink1() {
        return (ViewLinkImpl)findViewLink("HierarchyChildSelfLink1");
    }

    /**
     * Container's getter for RetiredNmqCmqprevUsedReport1.
     * @return RetiredNmqCmqprevUsedReport1
     */
    public ViewObjectImpl getRetiredNmqCmqPrevUsedReport() {
        return (ViewObjectImpl)findViewObject("RetiredNmqCmqPrevUsedReport");
    }

    /**
     * Container's getter for CrsRiskBaseVO.
     * @return CrsRiskBaseVO
     */
    public ViewObjectImpl getCrsRiskBaseVO() {
        return (ViewObjectImpl)findViewObject("CrsRiskBaseVO");
    }
     
    /**
     * Container's getter for CrsContentBaseVO1.
     * @return CrsContentBaseVO1
     */
    public ViewObjectImpl getCrsContentBaseVO() {
        return (ViewObjectImpl)findViewObject("CrsContentBaseVO");
    }
    
    /**
     * Refresh repository by calling crs_tms_sync function call.
     * Blue ball will be shown on the UI if TMS_UPDATE_FLAG is Y
     */
    public boolean refreshRepository(Long crsId) {
        //Execute the function call.
        DBTransaction txn = getDBTransaction();
        OracleCallableStatement cstmt = null;
        String cs = null;
        String returnCode = null;
        if (crsId != null) {
            cs = "{?=call CRS_UI_TMS_UTILS.CRS_TMS_SYNC (?)}";
            cstmt = (OracleCallableStatement)txn.createCallableStatement(cs, DBTransaction.DEFAULT);
            try {
                cstmt.registerOutParameter(1, Types.VARCHAR);
                cstmt.setNUMBER(2, new oracle.jbo.domain.Number(crsId));
                cstmt.execute();
                returnCode = cstmt.getString(1);

                if ("0".equalsIgnoreCase(returnCode)) {
                    //Reexecute the VO
                    initRiskRelation(crsId, "P");
                    return true;
                } else
                    return false;
            } catch (Exception e) {
                return false;
            } finally {
                try {
                    if (cstmt != null && !cstmt.isClosed())
                        cstmt.close();
                } catch (Exception e) {
                    throw new JboException(e);
                }
            }
        } else
            return true;
    }
    
    /**
     * Activate crs function call.
     */
    public String activateCrs(Long pCRSId,String pReasonForChange) {
        //Execute the function call.
        DBTransaction txn = getDBTransaction();
        OracleCallableStatement cstmt = null;
        String cs = null;
        String returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
        if (pCRSId != null) {
            cs = "{?=call CRS_UI_TMS_UTILS.activate_crs(?,?)}";
            cstmt = (OracleCallableStatement)txn.createCallableStatement(cs, DBTransaction.DEFAULT);
            try {
                cstmt.registerOutParameter(1, Types.VARCHAR);
                cstmt.setNUMBER(2, new oracle.jbo.domain.Number(pCRSId));
                cstmt.setString(3, pReasonForChange);
                cstmt.execute();
                returnMessage = cstmt.getString(1);

            } catch (Exception e) {
                returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
            } finally {
                try {
                    if (cstmt != null && !cstmt.isClosed())
                        cstmt.close();
                } catch (Exception e) {
                    throw new JboException(e);
                }
            }
        } else
            returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
        return returnMessage;
    }
    
    /**
     * MODIFY_CRS function call.
     */
    public String modifyCrs(Long pCRSId,String pReasonForChange) {
        //Execute the function call.
        DBTransaction txn = getDBTransaction();
        OracleCallableStatement cstmt = null;
        String cs = null;
        String returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
        if (pCRSId != null) {
            cs = "{?=call CRS_UI_TMS_UTILS.MODIFY_CRS(?,?)}";
            cstmt = (OracleCallableStatement)txn.createCallableStatement(cs, DBTransaction.DEFAULT);
            try {
                cstmt.registerOutParameter(1, Types.VARCHAR);
                cstmt.setNUMBER(2, new oracle.jbo.domain.Number(pCRSId));
                cstmt.setString(3, pReasonForChange);
                cstmt.execute();
                returnMessage = cstmt.getString(1);

            } catch (Exception e) {
                returnMessage = ModelConstants.PLSQL_CALL_FAILURE;                
            } finally {
                try {
                    if (cstmt != null && !cstmt.isClosed())
                        cstmt.close();
                } catch (Exception e) {
                    throw new JboException(e);
                }
            }
        } else
            returnMessage = ModelConstants.PLSQL_CALL_SUCCESS;
        return returnMessage;
    }
    
    /**
     * Activate crs_tms_sync function call.
     */
    public String retireCrs(Long pCRSId,String pReasonForChange) {
        //Execute the function call.
        ViewObjectImpl baseVO = this.getCrsContentBaseVO();
        DBTransaction txn = getDBTransaction();
        OracleCallableStatement cstmt = null;
        String cs = null;
        String returnCode = null;
        String returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
        if (pCRSId != null) {
            cs = "{?=call CRS_UI_TMS_UTILS.retire_crs (?,?)}";
            cstmt = (OracleCallableStatement)txn.createCallableStatement(cs, DBTransaction.DEFAULT);
            try {
                cstmt.registerOutParameter(1, Types.VARCHAR);
                cstmt.setNUMBER(2, new oracle.jbo.domain.Number(pCRSId));
                cstmt.setString(3, pReasonForChange);
                cstmt.execute();
                returnMessage = cstmt.getString(1);
                baseVO.executeQuery();
            } catch (Exception e) {
               // e.printStackTrace();
                returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
            } finally {
                try {
                    if (cstmt != null && !cstmt.isClosed())
                        cstmt.close();
                } catch (Exception e) {
                    throw new JboException(e);
                }
            }
        } else
            returnMessage = ModelConstants.PLSQL_CALL_SUCCESS;
       return returnMessage;
    }
    
    /**
     * Activate crs_tms_sync function call.
     */
    public String reactivateCrs(Long pCRSId,String pReasonForChange) {
        //Execute the function call.
        ViewObjectImpl baseVO = this.getCrsContentBaseVO();
        DBTransaction txn = getDBTransaction();
        OracleCallableStatement cstmt = null;
        String cs = null;
        String returnCode = null;
        String returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
        if (pCRSId != null) {
            cs = "{?=call CRS_UI_TMS_UTILS.reactivate_crs (?,?)}";
            cstmt = (OracleCallableStatement)txn.createCallableStatement(cs, DBTransaction.DEFAULT);
            try {
                cstmt.registerOutParameter(1, Types.VARCHAR);
                cstmt.setNUMBER(2, new oracle.jbo.domain.Number(pCRSId));
                cstmt.setString(3, pReasonForChange);
                cstmt.execute();
                returnMessage = cstmt.getString(1);
                baseVO.executeQuery();
            } catch (Exception e) {
               // e.printStackTrace();
               returnMessage = ModelConstants.PLSQL_CALL_FAILURE;
            } finally {
                try {
                    if (cstmt != null && !cstmt.isClosed())
                        cstmt.close();
                } catch (Exception e) {
                    throw new JboException(e);
                }
            }
        } else
           returnMessage = ModelConstants.PLSQL_CALL_SUCCESS;
        return returnMessage;
    }

    /**
     * Container's getter for FetchCrsContentBaseVO.
     * @return FetchCrsContentBaseVO
     */
    public ViewObjectImpl getFetchCrsContentBaseVO() {
        return (ViewObjectImpl)findViewObject("FetchCrsContentBaseVO");
    }

    /**
     * Return true if crsid found in staging VO
     * @param pCrsId
     * @return
     */
    public boolean findByCrsFromStg(Long pCrsId){
        ViewObjectImpl stgVO = this.getCrsContentVO();
        ViewCriteria vc = stgVO.getViewCriteria("findByCrsId");
        stgVO.setNamedWhereClauseParam("pCrsId", pCrsId);
        stgVO.applyViewCriteria(vc);
        stgVO.executeQuery();

        if (stgVO.first() != null &&
            pCrsId.equals(stgVO.first().getAttribute("CrsId"))) {
            return true;
        }
        return false;
    }

    /**
     * Container's getter for DictionaryVO.
     * @return DictionaryVO
     */
    public ViewObjectImpl getDictionaryVO() {
        return (ViewObjectImpl)findViewObject("DictionaryVO");
    }
    
    /**
     * The MEDDRA dictionary version is fetched from the database once per session to show in the footer of every page.
     * This method fetches the latest version.
     *
     * @return - latest MEDDRA Version
     */
    public String fetchDictionaryVersion(){
        String version = "";
        ViewObject dictVO = getDictionaryVO();
        dictVO.executeQuery();
        if(dictVO.getEstimatedRowCount() > 0){
            version = (String)dictVO.first().getAttribute("DictVersion");
        }
        return version;
    }
    
    /**
     * This method is used to fetch the domain Id from domain name.
     * Used while copying risk defintions and copying routine defintions as the DB flat view contains Domain name while Domain ID needs to be stored in the risk relations table.
     *
     * @param domainName - DataDomain Name
     * @return - Domain Id
     */
    public Integer fetchDomainIdFromName(String domainName){
        Integer domainId = 0;
        ViewObject domainVO = this.getDomainVO();
        domainVO.setWhereClause("DOMAIN_NAME = '"+domainName+"'");
        domainVO.executeQuery();
        if(domainVO.getEstimatedRowCount() > 0){
            domainId = (Integer)domainVO.first().getAttribute("DomainId");
        }
        return domainId;
    }

    /**
     * Container's getter for DomainVO.
     * @return DomainVO
     */
    public ViewObjectImpl getDomainVO() {
        return (ViewObjectImpl)findViewObject("DomainVO");
    }

    /**
     * Container's getter for DomainsTransientVO.
     * @return DomainsTransientVO
     */
    public DomainsTransientVOImpl getDomainsTransientVO() {
        return (DomainsTransientVOImpl)findViewObject("DomainsTransientVO");
    }

    /**
     * Container's getter for CrsDomainsVO.
     * @return CrsDomainsVO
     */
    public ViewObjectImpl getCrsDomainsVO() {
        return (ViewObjectImpl)findViewObject("CrsDomainsVO");
    }

    /**
     * Container's getter for PurposeLegendStaticVO1.
     * @return PurposeLegendStaticVO1
     */
    public ViewObjectImpl getPurposeLegendStaticVO() {
        return (ViewObjectImpl)findViewObject("PurposeLegendStaticVO");
    }

    /**
     * Container's getter for UserRoleVO.
     * @return UserRoleVO
     */
    public ViewObjectImpl getUserRoleVO() {
        return (ViewObjectImpl)findViewObject("UserRoleVO");
    }

    /**
     * Container's getter for PTReportVO.
     * @return PTReportVO
     */
    public ViewObjectImpl getPTReportVO() {
        return (ViewObjectImpl)findViewObject("PTReportVO");
    }

    /**
     * Container's getter for UserFullNameVO1.
     * @return UserFullNameVO1
     */
    public ViewObjectImpl getUserFullNameVO() {
        return (ViewObjectImpl)findViewObject("UserFullNameVO");
    }
    
    public Boolean validateSafetyTopic(Long crsId, String safetyTopic, String rpList, Long crsRiskId, Integer domainId){
        ViewObject relationVO = this.getFetchCrsRiskRelationVO();
        relationVO.setWhereClause("CRS_ID = "+crsId+" and SAFETY_TOPIC_OF_INTEREST = '"+safetyTopic+"' and RISK_PURPOSE_LIST = '"+rpList+"' and DOMAIN_ID = "+domainId+" and CRS_RISK_ID <> "+crsRiskId);
        relationVO.executeQuery();
        if(relationVO.getEstimatedRowCount() > 0)
            return Boolean.TRUE;
        else
            return Boolean.FALSE;
    }

    /**
     * Container's getter for FetchCrsRiskRelationVO.
     * @return FetchCrsRiskRelationVO
     */
    public ViewObjectImpl getFetchCrsRiskRelationVO() {
        return (ViewObjectImpl)findViewObject("FetchCrsRiskRelationVO");
    }

    /**
     * Container's getter for DesigneeFullNameVO1.
     * @return DesigneeFullNameVO1
     */
    public ViewObjectImpl getDesigneeFullNameVO() {
        return (ViewObjectImpl)findViewObject("DesigneeFullNameVO");
    }
}
