package com.novartis.ecrs.model.view.base;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 03 18:10:03 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsContentBaseVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CrsId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCrsId((Long)value);
            }
        }
        ,
        CrsName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCrsName((String)value);
            }
        }
        ,
        StateId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getStateId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setStateId((Integer)value);
            }
        }
        ,
        CompoundId {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCompoundId();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCompoundId((Integer)value);
            }
        }
        ,
        GenericName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getGenericName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setGenericName((String)value);
            }
        }
        ,
        TradeName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTradeName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setTradeName((String)value);
            }
        }
        ,
        Indication {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getIndication();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setIndication((String)value);
            }
        }
        ,
        IsMarketedFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getIsMarketedFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setIsMarketedFlag((String)value);
            }
        }
        ,
        ReleaseStatusFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getReleaseStatusFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setReleaseStatusFlag((String)value);
            }
        }
        ,
        BslName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getBslName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setBslName((String)value);
            }
        }
        ,
        Designee {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getDesignee();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setDesignee((String)value);
            }
        }
        ,
        MqmComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMqmComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setMqmComment((String)value);
            }
        }
        ,
        TaslName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTaslName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setTaslName((String)value);
            }
        }
        ,
        TaslRejectComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTaslRejectComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setTaslRejectComment((String)value);
            }
        }
        ,
        MedicalLeadName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMedicalLeadName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setMedicalLeadName((String)value);
            }
        }
        ,
        MedicalLeadRejectComment {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMedicalLeadRejectComment();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setMedicalLeadRejectComment((String)value);
            }
        }
        ,
        CrsEffectiveDt {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsEffectiveDt();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCrsEffectiveDt((Timestamp)value);
            }
        }
        ,
        ReviewApproveRequiredFlag {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getReviewApproveRequiredFlag();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setReviewApproveRequiredFlag((String)value);
            }
        }
        ,
        UiVersionNumber {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getUiVersionNumber();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setUiVersionNumber((Integer)value);
            }
        }
        ,
        CrsCompoundType {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsCompoundType();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCrsCompoundType((String)value);
            }
        }
        ,
        CrsCompoundCode {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCrsCompoundCode();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCrsCompoundCode((String)value);
            }
        }
        ,
        StateName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getStateName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setStateName((String)value);
            }
        }
        ,
        DesigneeName {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getDesigneeName();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setDesigneeName((String)value);
            }
        }
        ,
        CreationTs {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getCreationTs();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setCreationTs((Timestamp)value);
            }
        }
        ,
        ModificationTs {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getModificationTs();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setModificationTs((Timestamp)value);
            }
        }
        ,
        BSLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getBSLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TASLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getTASLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MLUserVA {
            public Object get(CrsContentBaseVORowImpl obj) {
                return obj.getMLUserVA();
            }

            public void put(CrsContentBaseVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CrsContentBaseVORowImpl object);

        public abstract void put(CrsContentBaseVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CRSID = AttributesEnum.CrsId.index();
    public static final int CRSNAME = AttributesEnum.CrsName.index();
    public static final int STATEID = AttributesEnum.StateId.index();
    public static final int COMPOUNDID = AttributesEnum.CompoundId.index();
    public static final int GENERICNAME = AttributesEnum.GenericName.index();
    public static final int TRADENAME = AttributesEnum.TradeName.index();
    public static final int INDICATION = AttributesEnum.Indication.index();
    public static final int ISMARKETEDFLAG = AttributesEnum.IsMarketedFlag.index();
    public static final int RELEASESTATUSFLAG = AttributesEnum.ReleaseStatusFlag.index();
    public static final int BSLNAME = AttributesEnum.BslName.index();
    public static final int DESIGNEE = AttributesEnum.Designee.index();
    public static final int MQMCOMMENT = AttributesEnum.MqmComment.index();
    public static final int TASLNAME = AttributesEnum.TaslName.index();
    public static final int TASLREJECTCOMMENT = AttributesEnum.TaslRejectComment.index();
    public static final int MEDICALLEADNAME = AttributesEnum.MedicalLeadName.index();
    public static final int MEDICALLEADREJECTCOMMENT = AttributesEnum.MedicalLeadRejectComment.index();
    public static final int CRSEFFECTIVEDT = AttributesEnum.CrsEffectiveDt.index();
    public static final int REVIEWAPPROVEREQUIREDFLAG = AttributesEnum.ReviewApproveRequiredFlag.index();
    public static final int UIVERSIONNUMBER = AttributesEnum.UiVersionNumber.index();
    public static final int CRSCOMPOUNDTYPE = AttributesEnum.CrsCompoundType.index();
    public static final int CRSCOMPOUNDCODE = AttributesEnum.CrsCompoundCode.index();
    public static final int STATENAME = AttributesEnum.StateName.index();
    public static final int DESIGNEENAME = AttributesEnum.DesigneeName.index();
    public static final int CREATIONTS = AttributesEnum.CreationTs.index();
    public static final int MODIFICATIONTS = AttributesEnum.ModificationTs.index();
    public static final int BSLUSERVA = AttributesEnum.BSLUserVA.index();
    public static final int TASLUSERVA = AttributesEnum.TASLUserVA.index();
    public static final int MLUSERVA = AttributesEnum.MLUserVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsContentBaseVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CrsId.
     * @return the CrsId
     */
    public Long getCrsId() {
        return (Long) getAttributeInternal(CRSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CrsId.
     * @param value value to set the  CrsId
     */
    public void setCrsId(Long value) {
        setAttributeInternal(CRSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CrsName.
     * @return the CrsName
     */
    public String getCrsName() {
        return (String) getAttributeInternal(CRSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CrsName.
     * @param value value to set the  CrsName
     */
    public void setCrsName(String value) {
        setAttributeInternal(CRSNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StateId.
     * @return the StateId
     */
    public Integer getStateId() {
        return (Integer) getAttributeInternal(STATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StateId.
     * @param value value to set the  StateId
     */
    public void setStateId(Integer value) {
        setAttributeInternal(STATEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompoundId.
     * @return the CompoundId
     */
    public Integer getCompoundId() {
        return (Integer) getAttributeInternal(COMPOUNDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompoundId.
     * @param value value to set the  CompoundId
     */
    public void setCompoundId(Integer value) {
        setAttributeInternal(COMPOUNDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GenericName.
     * @return the GenericName
     */
    public String getGenericName() {
        return (String) getAttributeInternal(GENERICNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GenericName.
     * @param value value to set the  GenericName
     */
    public void setGenericName(String value) {
        setAttributeInternal(GENERICNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TradeName.
     * @return the TradeName
     */
    public String getTradeName() {
        return (String) getAttributeInternal(TRADENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TradeName.
     * @param value value to set the  TradeName
     */
    public void setTradeName(String value) {
        setAttributeInternal(TRADENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Indication.
     * @return the Indication
     */
    public String getIndication() {
        return (String) getAttributeInternal(INDICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Indication.
     * @param value value to set the  Indication
     */
    public void setIndication(String value) {
        setAttributeInternal(INDICATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsMarketedFlag.
     * @return the IsMarketedFlag
     */
    public String getIsMarketedFlag() {
        return (String) getAttributeInternal(ISMARKETEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsMarketedFlag.
     * @param value value to set the  IsMarketedFlag
     */
    public void setIsMarketedFlag(String value) {
        setAttributeInternal(ISMARKETEDFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReleaseStatusFlag.
     * @return the ReleaseStatusFlag
     */
    public String getReleaseStatusFlag() {
        return (String) getAttributeInternal(RELEASESTATUSFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReleaseStatusFlag.
     * @param value value to set the  ReleaseStatusFlag
     */
    public void setReleaseStatusFlag(String value) {
        setAttributeInternal(RELEASESTATUSFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BslName.
     * @return the BslName
     */
    public String getBslName() {
        return (String) getAttributeInternal(BSLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BslName.
     * @param value value to set the  BslName
     */
    public void setBslName(String value) {
        setAttributeInternal(BSLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Designee.
     * @return the Designee
     */
    public String getDesignee() {
        return (String) getAttributeInternal(DESIGNEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Designee.
     * @param value value to set the  Designee
     */
    public void setDesignee(String value) {
        setAttributeInternal(DESIGNEE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MqmComment.
     * @return the MqmComment
     */
    public String getMqmComment() {
        return (String) getAttributeInternal(MQMCOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MqmComment.
     * @param value value to set the  MqmComment
     */
    public void setMqmComment(String value) {
        setAttributeInternal(MQMCOMMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaslName.
     * @return the TaslName
     */
    public String getTaslName() {
        return (String) getAttributeInternal(TASLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaslName.
     * @param value value to set the  TaslName
     */
    public void setTaslName(String value) {
        setAttributeInternal(TASLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaslRejectComment.
     * @return the TaslRejectComment
     */
    public String getTaslRejectComment() {
        return (String) getAttributeInternal(TASLREJECTCOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaslRejectComment.
     * @param value value to set the  TaslRejectComment
     */
    public void setTaslRejectComment(String value) {
        setAttributeInternal(TASLREJECTCOMMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MedicalLeadName.
     * @return the MedicalLeadName
     */
    public String getMedicalLeadName() {
        return (String) getAttributeInternal(MEDICALLEADNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MedicalLeadName.
     * @param value value to set the  MedicalLeadName
     */
    public void setMedicalLeadName(String value) {
        setAttributeInternal(MEDICALLEADNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MedicalLeadRejectComment.
     * @return the MedicalLeadRejectComment
     */
    public String getMedicalLeadRejectComment() {
        return (String) getAttributeInternal(MEDICALLEADREJECTCOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MedicalLeadRejectComment.
     * @param value value to set the  MedicalLeadRejectComment
     */
    public void setMedicalLeadRejectComment(String value) {
        setAttributeInternal(MEDICALLEADREJECTCOMMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CrsEffectiveDt.
     * @return the CrsEffectiveDt
     */
    public Timestamp getCrsEffectiveDt() {
        return (Timestamp) getAttributeInternal(CRSEFFECTIVEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CrsEffectiveDt.
     * @param value value to set the  CrsEffectiveDt
     */
    public void setCrsEffectiveDt(Timestamp value) {
        setAttributeInternal(CRSEFFECTIVEDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReviewApproveRequiredFlag.
     * @return the ReviewApproveRequiredFlag
     */
    public String getReviewApproveRequiredFlag() {
        return (String) getAttributeInternal(REVIEWAPPROVEREQUIREDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReviewApproveRequiredFlag.
     * @param value value to set the  ReviewApproveRequiredFlag
     */
    public void setReviewApproveRequiredFlag(String value) {
        setAttributeInternal(REVIEWAPPROVEREQUIREDFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UiVersionNumber.
     * @return the UiVersionNumber
     */
    public Integer getUiVersionNumber() {
        return (Integer) getAttributeInternal(UIVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UiVersionNumber.
     * @param value value to set the  UiVersionNumber
     */
    public void setUiVersionNumber(Integer value) {
        setAttributeInternal(UIVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CrsCompoundType.
     * @return the CrsCompoundType
     */
    public String getCrsCompoundType() {
        return (String) getAttributeInternal(CRSCOMPOUNDTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CrsCompoundType.
     * @param value value to set the  CrsCompoundType
     */
    public void setCrsCompoundType(String value) {
        setAttributeInternal(CRSCOMPOUNDTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CrsCompoundCode.
     * @return the CrsCompoundCode
     */
    public String getCrsCompoundCode() {
        return (String) getAttributeInternal(CRSCOMPOUNDCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CrsCompoundCode.
     * @param value value to set the  CrsCompoundCode
     */
    public void setCrsCompoundCode(String value) {
        setAttributeInternal(CRSCOMPOUNDCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StateName.
     * @return the StateName
     */
    public String getStateName() {
        return (String) getAttributeInternal(STATENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StateName.
     * @param value value to set the  StateName
     */
    public void setStateName(String value) {
        setAttributeInternal(STATENAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute DesigneeName.
     * @return the DesigneeName
     */
    public String getDesigneeName() {
        return (String) getAttributeInternal(DESIGNEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DesigneeName.
     * @param value value to set the  DesigneeName
     */
    public void setDesigneeName(String value) {
        setAttributeInternal(DESIGNEENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationTs.
     * @return the CreationTs
     */
    public Timestamp getCreationTs() {
        return (Timestamp) getAttributeInternal(CREATIONTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationTs.
     * @param value value to set the  CreationTs
     */
    public void setCreationTs(Timestamp value) {
        setAttributeInternal(CREATIONTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ModificationTs.
     * @return the ModificationTs
     */
    public Timestamp getModificationTs() {
        return (Timestamp) getAttributeInternal(MODIFICATIONTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ModificationTs.
     * @param value value to set the  ModificationTs
     */
    public void setModificationTs(Timestamp value) {
        setAttributeInternal(MODIFICATIONTS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BSLUserVA.
     */
    public RowSet getBSLUserVA() {
        return (RowSet)getAttributeInternal(BSLUSERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TASLUserVA.
     */
    public RowSet getTASLUserVA() {
        return (RowSet)getAttributeInternal(TASLUSERVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MLUserVA.
     */
    public RowSet getMLUserVA() {
        return (RowSet)getAttributeInternal(MLUSERVA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
