package com.novartis.ecrs.model.entity;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 12 18:38:27 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsRolesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        RoleId {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getRoleId();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setRoleId((Integer)value);
            }
        }
        ,
        RoleName {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getRoleName();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setRoleName((String)value);
            }
        }
        ,
        RoleDesc {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getRoleDesc();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setRoleDesc((String)value);
            }
        }
        ,
        OracleRoleName {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getOracleRoleName();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setOracleRoleName((String)value);
            }
        }
        ,
        ActiveFlag {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getActiveFlag();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setActiveFlag((String)value);
            }
        }
        ,
        CrsUserRolesEO {
            public Object get(CrsRolesEOImpl obj) {
                return obj.getCrsUserRolesEO();
            }

            public void put(CrsRolesEOImpl obj, Object value) {
                obj.setCrsUserRolesEO((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CrsRolesEOImpl object);

        public abstract void put(CrsRolesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int ROLEDESC = AttributesEnum.RoleDesc.index();
    public static final int ORACLEROLENAME = AttributesEnum.OracleRoleName.index();
    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CRSUSERROLESEO = AttributesEnum.CrsUserRolesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsRolesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.novartis.ecrs.model.entity.CrsRolesEO");
    }

    /**
     * Gets the attribute value for RoleId, using the alias name RoleId.
     * @return the value of RoleId
     */
    public Integer getRoleId() {
        return (Integer)getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoleId.
     * @param value value to set the RoleId
     */
    public void setRoleId(Integer value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for RoleName, using the alias name RoleName.
     * @return the value of RoleName
     */
    public String getRoleName() {
        return (String)getAttributeInternal(ROLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoleName.
     * @param value value to set the RoleName
     */
    public void setRoleName(String value) {
        setAttributeInternal(ROLENAME, value);
    }

    /**
     * Gets the attribute value for RoleDesc, using the alias name RoleDesc.
     * @return the value of RoleDesc
     */
    public String getRoleDesc() {
        return (String)getAttributeInternal(ROLEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for RoleDesc.
     * @param value value to set the RoleDesc
     */
    public void setRoleDesc(String value) {
        setAttributeInternal(ROLEDESC, value);
    }

    /**
     * Gets the attribute value for OracleRoleName, using the alias name OracleRoleName.
     * @return the value of OracleRoleName
     */
    public String getOracleRoleName() {
        return (String)getAttributeInternal(ORACLEROLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for OracleRoleName.
     * @param value value to set the OracleRoleName
     */
    public void setOracleRoleName(String value) {
        setAttributeInternal(ORACLEROLENAME, value);
    }

    /**
     * Gets the attribute value for ActiveFlag, using the alias name ActiveFlag.
     * @return the value of ActiveFlag
     */
    public String getActiveFlag() {
        return (String)getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveFlag.
     * @param value value to set the ActiveFlag
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCrsUserRolesEO() {
        return (EntityImpl)getAttributeInternal(CRSUSERROLESEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCrsUserRolesEO(EntityImpl value) {
        setAttributeInternal(CRSUSERROLESEO, value);
    }


    /**
     * @param roleId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer roleId) {
        return new Key(new Object[]{roleId});
    }

    public void doDML(int operation, TransactionEvent e) {
        if(operation == DML_INSERT)
            this.setRoleId((Integer)(new SequenceImpl("crs_roles_seq",getDBTransaction()).getSequenceNumber()).intValue());
        super.doDML(operation, e);
    }
}
