package com.novartis.ecrs.model.entity;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 12 19:27:30 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsStateEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StateId {
            public Object get(CrsStateEOImpl obj) {
                return obj.getStateId();
            }

            public void put(CrsStateEOImpl obj, Object value) {
                obj.setStateId((Integer)value);
            }
        }
        ,
        StateName {
            public Object get(CrsStateEOImpl obj) {
                return obj.getStateName();
            }

            public void put(CrsStateEOImpl obj, Object value) {
                obj.setStateName((String)value);
            }
        }
        ,
        StateDesc {
            public Object get(CrsStateEOImpl obj) {
                return obj.getStateDesc();
            }

            public void put(CrsStateEOImpl obj, Object value) {
                obj.setStateDesc((String)value);
            }
        }
        ,
        CrsContentEO {
            public Object get(CrsStateEOImpl obj) {
                return obj.getCrsContentEO();
            }

            public void put(CrsStateEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CrsStateEOImpl object);

        public abstract void put(CrsStateEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int STATEID = AttributesEnum.StateId.index();
    public static final int STATENAME = AttributesEnum.StateName.index();
    public static final int STATEDESC = AttributesEnum.StateDesc.index();
    public static final int CRSCONTENTEO = AttributesEnum.CrsContentEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CrsStateEOImpl() {
    }

    /**
     * Gets the attribute value for StateId, using the alias name StateId.
     * @return the value of StateId
     */
    public Integer getStateId() {
        return (Integer)getAttributeInternal(STATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateId.
     * @param value value to set the StateId
     */
    public void setStateId(Integer value) {
        setAttributeInternal(STATEID, value);
    }

    /**
     * Gets the attribute value for StateName, using the alias name StateName.
     * @return the value of StateName
     */
    public String getStateName() {
        return (String)getAttributeInternal(STATENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateName.
     * @param value value to set the StateName
     */
    public void setStateName(String value) {
        setAttributeInternal(STATENAME, value);
    }

    /**
     * Gets the attribute value for StateDesc, using the alias name StateDesc.
     * @return the value of StateDesc
     */
    public String getStateDesc() {
        return (String)getAttributeInternal(STATEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateDesc.
     * @param value value to set the StateDesc
     */
    public void setStateDesc(String value) {
        setAttributeInternal(STATEDESC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCrsContentEO() {
        return (RowIterator)getAttributeInternal(CRSCONTENTEO);
    }

    /**
     * @param stateId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer stateId) {
        return new Key(new Object[]{stateId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.novartis.ecrs.model.entity.CrsStateEO");
    }
    
    public void doDML(int operation, TransactionEvent e) {
        if(operation == DML_INSERT)
            this.setStateId((Integer)(new SequenceImpl("crs_states_seq",getDBTransaction()).getSequenceNumber()).intValue());
        super.doDML(operation, e);
    }
}
