package com.novartis.ecrs.model.am.client;

import com.novartis.ecrs.model.am.common.ECRSAppModule;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 11 22:15:43 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ECRSAppModuleClient extends ApplicationModuleImpl implements ECRSAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ECRSAppModuleClient() {
    }


    public void copyCurrentRiskRelation(Long srcRiskId, Long destCrsId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyCurrentRiskRelation",new String [] {"java.lang.Long","java.lang.Long"},new Object[] {srcRiskId, destCrsId});
        return;
    }

    public void copyRoutineDefinition(Long crsId) {
        Object _ret = this.riInvokeExportedMethod(this,"copyRoutineDefinition",new String [] {"java.lang.Long"},new Object[] {crsId});
        return;
    }

    public void deleteCrs() {
        Object _ret = this.riInvokeExportedMethod(this,"deleteCrs",null,null);
        return;
    }

    public List fetchDatabases() {
        Object _ret = this.riInvokeExportedMethod(this,"fetchDatabases",null,null);
        return (List)_ret;
    }

    public List fetchDesignees() {
        Object _ret = this.riInvokeExportedMethod(this,"fetchDesignees",null,null);
        return (List)_ret;
    }

    public void filterCRSContent(String userInRole, String userName, boolean isInboxDisable) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterCRSContent",new String [] {"java.lang.String","java.lang.String","boolean"},new Object[] {userInRole, userName, new Boolean(isInboxDisable)});
        return;
    }

    public void initRiskRelation(Long crsId) {
        Object _ret = this.riInvokeExportedMethod(this,"initRiskRelation",new String [] {"java.lang.Long"},new Object[] {crsId});
        return;
    }
}
