package com.novartis.ecrs.model.am.client;

import com.novartis.ecrs.model.am.common.ECRSAppModule;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 03 13:34:24 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ECRSAppModuleClient extends ApplicationModuleImpl implements ECRSAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ECRSAppModuleClient() {
    }


    public boolean activateCrs(Long pCRSId, String pReasonForChange) {
        Object _ret =
            this.riInvokeExportedMethod(this,"activateCrs",new String [] {"java.lang.Long","java.lang.String"},new Object[] {pCRSId, pReasonForChange});
        return ((Boolean)_ret).booleanValue();
    }

    public void copyCurrentRiskRelation(Long srcRiskId, Long destCrsId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyCurrentRiskRelation",new String [] {"java.lang.Long","java.lang.Long"},new Object[] {srcRiskId, destCrsId});
        return;
    }

    public void copyRoutineDefinition(Long crsId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyRoutineDefinition",new String [] {"java.lang.Long"},new Object[] {crsId});
        return;
    }

    public void deleteCrs() {
        Object _ret = this.riInvokeExportedMethod(this,"deleteCrs",null,null);
        return;
    }

    public List fetchDatabases() {
        Object _ret = this.riInvokeExportedMethod(this,"fetchDatabases",null,null);
        return (List)_ret;
    }

    public List fetchDesignees() {
        Object _ret = this.riInvokeExportedMethod(this,"fetchDesignees",null,null);
        return (List)_ret;
    }

    public void filterCRSContent(String userInRole, String userName,
                                 boolean isInboxDisable) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterCRSContent",new String [] {"java.lang.String","java.lang.String","boolean"},new Object[] {userInRole, userName, new Boolean(isInboxDisable)});
        return;
    }

    public boolean findByCrsFromStg(Long pCrsId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findByCrsFromStg",new String [] {"java.lang.Long"},new Object[] {pCrsId});
        return ((Boolean)_ret).booleanValue();
    }

    public void initRiskRelation(Long crsId, String status) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initRiskRelation",new String [] {"java.lang.Long","java.lang.String"},new Object[] {crsId, status});
        return;
    }

    public String modifyCrs(Long pCRSId, String pReasonForChange) {
        Object _ret =
            this.riInvokeExportedMethod(this,"modifyCrs",new String [] {"java.lang.Long","java.lang.String"},new Object[] {pCRSId, pReasonForChange});
        return (String)_ret;
    }

    public String reactivateCrs(Long pCRSId, String pReasonForChange) {
        Object _ret =
            this.riInvokeExportedMethod(this,"reactivateCrs",new String [] {"java.lang.Long","java.lang.String"},new Object[] {pCRSId, pReasonForChange});
        return (String)_ret;
    }

    public boolean refreshRepository(Long crsId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshRepository",new String [] {"java.lang.Long"},new Object[] {crsId});
        return ((Boolean)_ret).booleanValue();
    }

    public String retireCrs(Long pCRSId, String pReasonForChange) {
        Object _ret =
            this.riInvokeExportedMethod(this,"retireCrs",new String [] {"java.lang.Long","java.lang.String"},new Object[] {pCRSId, pReasonForChange});
        return (String)_ret;
    }
}
